/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrackRequestRouteImport } from './routes/track-request'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRequestRoute = TrackRequestRouteImport.update({
  id: '/track-request',
  path: '/track-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/orders': typeof OrdersRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/support': typeof SupportRoute
  '/track-request': typeof TrackRequestRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/orders': typeof OrdersRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/support': typeof SupportRoute
  '/track-request': typeof TrackRequestRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/orders': typeof OrdersRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/support': typeof SupportRoute
  '/track-request': typeof TrackRequestRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/login': typeof AdminLoginRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/favorites'
    | '/orders'
    | '/returns'
    | '/shipping'
    | '/support'
    | '/track-request'
    | '/admin/$'
    | '/admin/login'
    | '/product/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/favorites'
    | '/orders'
    | '/returns'
    | '/shipping'
    | '/support'
    | '/track-request'
    | '/admin/$'
    | '/admin/login'
    | '/product/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/favorites'
    | '/orders'
    | '/returns'
    | '/shipping'
    | '/support'
    | '/track-request'
    | '/admin/$'
    | '/admin/login'
    | '/product/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  OrdersRoute: typeof OrdersRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  SupportRoute: typeof SupportRoute
  TrackRequestRoute: typeof TrackRequestRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-request': {
      id: '/track-request'
      path: '/track-request'
      fullPath: '/track-request'
      preLoaderRoute: typeof TrackRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  OrdersRoute: OrdersRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  SupportRoute: SupportRoute,
  TrackRequestRoute: TrackRequestRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
